### ISSUE TITLE
Quickfix window is split on the wrong side

### ISSUE THREAD

**Issue by cryptomilk** [beauwilliams/focus.nvim#24] opened 2021-08-09 14:01 UTC
If you have one vsplit and you're on the left window. The quickfix windows ist opened on the right, it should be on the left.

**Comment by beauwilliams** [comment] 2021-08-09 16:39
I don't think its caused by this plugin because I did try rm -rf focus.lua and ran `nvim -u NORC` and still had the qf list open on the right. Weird behaviour however

**Comment by cryptomilk** [comment] 2021-08-10 16:52
Might be worth to report upstream ...

**Comment by beauwilliams** [comment] 2021-08-11 03:07
Yeah good idea, it could be added to nvim core. Might even be worth a pr if I can find some time.

**Comment by beauwilliams** [comment] 2021-09-09 11:57
Closing for now. I think perhaps this is a fix that can be taken upstream. I referenced a interim solution in readme faq

**Closed by beauwilliams** 2021-09-09 11:57 UTC
