### ISSUE TITLE
Feature request: nvim-spectre support

### ISSUE THREAD

**Issue by piersolenski** [beauwilliams/focus.nvim#43] opened 2021-09-14 15:05 UTC
Would be awesome to support https://github.com/windwp/nvim-spectre - I haven't found a way to get it working properly with the setup so far, any guidance would be appreciated!

**Comment by beauwilliams** [comment] 2021-09-14 23:45
I've noticed this is similar to #42 

You can try this. Let me know how it works for you. It seems to solve the issue on my end for now. Make sure to update focus first 👍 

```lua
vim.cmd([[
function! SpectreFocus()
    lua vim.bo.buftype = 'help'
    lua require('spectre').open()
endfunction
nnoremap <leader>S :call SpectreFocus()<cr>
]])
```

**Comment by beauwilliams** [comment] 2021-09-16 12:16
I pushed a fix that sets it to 70 width when entering insert mode. I have come across some troubles reading the filetype when spectre is opened. It seems that on BufEnter event, it gets the old filetype

**Comment by piersolenski** [comment] 2021-09-19 16:47
Hmm that first fix kind of works with one window, but not in a vertical split:
![image](https://user-images.githubusercontent.com/1285419/133935718-90e51ce5-2605-4170-92ec-3ec05aa5401b.png)
![image](https://user-images.githubusercontent.com/1285419/133935728-33fb58f4-ee15-451d-8684-e63581ce8873.png)

Setting it to 90 only works when `is_insert_mode = false` is set, and the initial incorrect size is still a bit jarring. Would it also be possible to change the value for smaller screens? Thanks!

**Comment by beauwilliams** [comment] 2021-09-19 22:55
I have found the problem is that spectre does not have a filetype set initially when it is first opened. I will see if I can open PR with spectre

**Comment by beauwilliams** [comment] 2021-09-20 00:54
> Hmm that first fix kind of works with one window, but not in a vertical split:
> 
> ![image](https://user-images.githubusercontent.com/1285419/133935718-90e51ce5-2605-4170-92ec-3ec05aa5401b.png)
> ![image](https://user-images.githubusercontent.com/1285419/133935728-33fb58f4-ee15-451d-8684-e63581ce8873.png)
> 
> Setting it to 90 only works when `is_insert_mode = false` is set, and the initial incorrect size is still a bit jarring. Would it also be possible to change the value for smaller screens? Thanks!

I've just pushed what I would do. It simply returns when filtetype=spectre_panel

The only problem is that spectre runs 'vnew' to create a new buffer, and so it initially has a '' (blank) filetype set. 

So only when first opening it will resize, after that it will have the 'spectre_panel' ft set and won't resize anymore.

**Comment by beauwilliams** [comment] 2021-09-20 02:22
I have found a way to deal with this edge case using defer_fn to wait for some time before checking filetype and running resize() in case its not set when buffer created (vim limitation)

What behaviour would you like? I found if we just exclude spectre from being resized, when having many splits it can get crushed. So I added a call to :FocusSplitEqualise

**Comment by cryptomilk** [comment] 2021-09-20 06:20
If you just enter a buffer, then the filetype isn't detected! If you want filetype detection you need to wait for the filetype event! See `help :event`and search for `FileType`! Just waiting isn't really a solution as you don't know how long you should wait. It depends on the load of the machine and hardware.

So you might want a function which runs on the filetype event and resizes probably.

**Comment by beauwilliams** [comment] 2021-09-20 11:10
I did try using a filetype event earlier and it did not seem to work unfortunately. I will give it another crack. I agree this is not an optimal way to handle the problem. I think ideally there would be a way to initialise a buffer with options set when it is created

**Comment by beauwilliams** [comment] 2021-09-20 11:19
I swear I tried this many times earlier but it works now.. 😅

**Comment by piersolenski** [comment] 2021-09-20 16:23
This works much better! The only problem is if you then navigate to another split and back again, you eventually end up with the same issue. This works well enough for my use case for now though - thanks!

**Comment by beauwilliams** [comment] 2021-09-21 00:06
Yeah that's a bit of a problem. There is one thing I have thought of adding. It could be useful for later is a function to check all buffers in the tab for a filetype etc. i.e if there is a 'spectre_panel' filtype in this tab, always keep the splits equalised.

That would solve the issue for when you move to other splits

**Comment by beauwilliams** [comment] 2022-07-24 08:18
Closing as this issue is resolved on my end.

**Closed by beauwilliams** 2022-07-24 08:18 UTC
Labels: good first issue, compatibility
