### ISSUE TITLE
The resizer doesn't work if the buffer doesn't have a filetype

### ISSUE THREAD

**Issue by cryptomilk** [beauwilliams/focus.nvim#48] opened 2021-09-18 17:08 UTC
If you have an empty buffer, the resizer doesn't resize the split, it only works for buffers with a filetype set!

**Comment by cryptomilk** [comment] 2021-09-18 17:11
Reproducer:

```
:vsplit
:enew
```

Then switch between splits several times.

**Comment by beauwilliams** [comment] 2021-09-18 23:20
I have this fixed in the new PR I expect to merge very soon 👍 

The problem is that the resizer was not very reliable using the vim.i.winwidth vars as they are globally mutable.

So I moved back to my original implementation to handling resizing within the resizer.

This meant that I can solve issues with i.e Snap fuzzy finder, without having to explicitly set the '' (blank) filetype to be excluded

**Comment by beauwilliams** [comment] 2021-09-18 23:43
This PR. Fixes this issue. https://github.com/beauwilliams/focus.nvim/pull/46

**Closed** 2021-09-19 00:08 UTC
Labels: bug
